
- name: Apply migrations
  env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
  run: |
    python - <<'PYCODE'
import os
import psycopg2
import glob
from urllib.parse import urlparse

database_url = os.getenv('DATABASE_URL')
conn = psycopg2.connect(database_url, sslmode='require')
conn.autocommit = True

with conn.cursor() as cur:
    print("Applying migrations...")
    for file in sorted(glob.glob('supabase/migrations/*.sql')):
        print(f"Running {file}")
        with open(file, 'r', encoding='utf-8') as f:
            sql = f.read()
            cur.execute(sql)

print("✅ All migrations applied successfully.")
conn.close()
PYCODE
